In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target,test_size=0.3)

KFold Cross Validation


In [3]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [4]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
  print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


KFold for digits example

In [10]:
def get_score(model, X_train, X_test, y_train, y_test):
  model.fit(X_train, y_train)
  return model.score(X_test, y_test)

In [16]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

s_logistic = []
s_svm = []
s_rf = []

for train_index, test_index in folds.split(digits.data, digits.target):
  X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
  s_logistic.append(get_score(LogisticRegression(solver='liblinear'),X_train,X_test,y_train,y_test))
  s_svm.append(get_score(SVC(gamma='auto'),X_train,X_test,y_train,y_test))
  s_rf.append(get_score(RandomForestClassifier(n_estimators=40),X_train,X_test,y_train,y_test))

cross_val_score function


In [18]:
from sklearn.model_selection import cross_val_score

cross_val_score(LogisticRegression(solver='liblinear'),digits.data,digits.target,cv=3)
cross_val_score(SVC(gamma='auto'),digits.data,digits.target,cv=3)
scores1=cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target,cv=3)

np.average(scores1)

0.9371174179187535